seed: 1
model:
    J1: 1
    J2: 1
    L: 16384
    h: 0
mc:
    T0: 2.7
    Tf: 2.4
    dT: .1
    Ntherm0: 500
    Ntherm: 100 # 200 # 300 # 500
    Nsamples: 5000
    Nsweeps: 100 # 100
    load_spins: 1
