seed: 5
model:
    J1: 1
    J2: 1
    L: 1024
    h: 0
mc:
    T0: 2.11
    Tf: 2.1
    dT: .01
    Ntherm0: 2000
    Ntherm: 700 # 300 # 500
    Nsamples: 10000
    Nsweeps: 1000 # 700
    load_spins: 1
